"""Fix Follow model

Revision ID: 362ce735c496
Revises: 
Create Date: 2024-07-28 06:16:09.880494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362ce735c496'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['userid'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['followed_id'], ['userid'], ondelete='CASCADE')
        batch_op.drop_column('follow_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follow_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['userid'])
        batch_op.create_foreign_key(None, 'user', ['followed_id'], ['userid'])
        batch_op.drop_column('timestamp')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
